import './globals.scss'
import type { Metadata } from 'next'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
// @ts-ignore
import { getServerSession } from 'next-auth'
import ClientProvider from '@/components/auth/client-provider'
import { config } from '@fortawesome/fontawesome-svg-core'
import ReduxProvider from '@/components/ReduxProvider'

config.autoAddCss = false



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" className="h-screen min-w-full">
      <body className="w-full h-full">
        <script src="https://accounts.google.com/gsi/client" async></script>
        <ClientProvider session={session}>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </ClientProvider>
      </body>
    </html>
  )
}
