name: Nest Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install app dependencies
        working-directory: ./backend
        run: npm install

      - name: Run ESLint
        working-directory: ./backend
        run: npm run lint

      - name: Prepare tests database
        working-directory: ./backend
        run: npm run docker:test:up && npm run prisma:deploy:migration:test

#      - name: Run unit test
#        working-directory: ./backend
#        run: npm run test:cov

      - name: Run acceptance tests
        working-directory: ./backend
        run: npm run test:acceptance

      - name: Run integration test
        working-directory: ./backend
        run: npm run test:integration

#      - name: Run e2e test
#        working-directory: ./backend
#        run: npm run test:e2e

      - name: Shut down tests database
        if: always()
        working-directory: ./backend
        run: npm run docker:test:down